class_map = {
    # classes of new TotalSegmentator v2
    "total": {
        1: "spleen",
        2: "kidney_right",
        3: "kidney_left",
        4: "gallbladder",
        5: "liver",
        6: "stomach",
        7: "pancreas",
        8: "adrenal_gland_right",
        9: "adrenal_gland_left",
        10: "lung_upper_lobe_left",
        11: "lung_lower_lobe_left",
        12: "lung_upper_lobe_right",
        13: "lung_middle_lobe_right",
        14: "lung_lower_lobe_right",
        15: "esophagus",
        16: "trachea",
        17: "thyroid_gland",
        18: "small_bowel",
        19: "duodenum",
        20: "colon",
        21: "urinary_bladder",
        22: "prostate",
        23: "kidney_cyst_left",
        24: "kidney_cyst_right",
        25: "sacrum",
        26: "vertebrae_S1",
        27: "vertebrae_L5",
        28: "vertebrae_L4",
        29: "vertebrae_L3",
        30: "vertebrae_L2",
        31: "vertebrae_L1",
        32: "vertebrae_T12",
        33: "vertebrae_T11",
        34: "vertebrae_T10",
        35: "vertebrae_T9",
        36: "vertebrae_T8",
        37: "vertebrae_T7",
        38: "vertebrae_T6",
        39: "vertebrae_T5",
        40: "vertebrae_T4",
        41: "vertebrae_T3",
        42: "vertebrae_T2",
        43: "vertebrae_T1",
        44: "vertebrae_C7",
        45: "vertebrae_C6",
        46: "vertebrae_C5",
        47: "vertebrae_C4",
        48: "vertebrae_C3",
        49: "vertebrae_C2",
        50: "vertebrae_C1",
        51: "heart",
        52: "aorta",
        53: "pulmonary_vein",
        54: "brachiocephalic_trunk",
        55: "subclavian_artery_right",
        56: "subclavian_artery_left",
        57: "common_carotid_artery_right",
        58: "common_carotid_artery_left",
        59: "brachiocephalic_vein_left",
        60: "brachiocephalic_vein_right",
        61: "atrial_appendage_left",
        62: "superior_vena_cava",
        63: "inferior_vena_cava",
        64: "portal_vein_and_splenic_vein",
        65: "iliac_artery_left",
        66: "iliac_artery_right",
        67: "iliac_vena_left",
        68: "iliac_vena_right",
        69: "humerus_left",
        70: "humerus_right",
        71: "scapula_left",
        72: "scapula_right",
        73: "clavicula_left",
        74: "clavicula_right",
        75: "femur_left",
        76: "femur_right",
        77: "hip_left",
        78: "hip_right",
        79: "spinal_cord",
        80: "gluteus_maximus_left",
        81: "gluteus_maximus_right",
        82: "gluteus_medius_left",
        83: "gluteus_medius_right",
        84: "gluteus_minimus_left",
        85: "gluteus_minimus_right",
        86: "autochthon_left",
        87: "autochthon_right",
        88: "iliopsoas_left",
        89: "iliopsoas_right",
        90: "brain",
        91: "skull",
        92: "rib_right_4",
        93: "rib_right_3",
        94: "rib_left_1",
        95: "rib_left_2",
        96: "rib_left_3",
        97: "rib_left_4",
        98: "rib_left_5",
        99: "rib_left_6",
        100: "rib_left_7",
        101: "rib_left_8",
        102: "rib_left_9",
        103: "rib_left_10",
        104: "rib_left_11",
        105: "rib_left_12",
        106: "rib_right_1",
        107: "rib_right_2",
        108: "rib_right_5",
        109: "rib_right_6",
        110: "rib_right_7",
        111: "rib_right_8",
        112: "rib_right_9",
        113: "rib_right_10",
        114: "rib_right_11",
        115: "rib_right_12",
        116: "sternum",
        117: "costal_cartilages"
    },
    # total_fast not extra class map, because easier to use just "total" for fast model
   
}


class_name = {
        1: "spleen",
        2: "right kidney",
        3: "left kidney",
        4: "gallbladder",
        5: "liver",
        6: "stomach",
        7: "pancreas",
        8: "right suprarenal gland",
        9: "left suprarenal gland",
        10: "superior lobe of left lung",
        11: "inferior lobe of left lung",
        12: "superior lobe of right lung",
        13: "middle lobe of right lung",
        14: "inferior lobe of right lung",
        15: "esophagus",
        16: "trachea",
        17: "thyroid gland",
        18: "small intestine",
        19: "duodenum",
        20: "colon",
        21: "urinary bladder",
        22: "prostate",
        23: "left kidney cyst",
        24: "right kidney cyst",
        25: "sacrum",
        26: "first sacral vertebrae",
        27: "fifth lumbar vertebrae",
        28: "fourth lumbar vertebrae",
        29: "third lumbar vertebrae",
        30: "second lumbar vertebrae",
        31: "first lumbar vertebrae",
        32: "twelfth thoracic vertebrae",
        33: "eleventh thoracic vertebrae",
        34: "tenth thoracic vertebrae",
        35: "ninth thoracic vertebrae",
        36: "eighth thoracic vertebrae",
        37: "seventh thoracic vertebrae",
        38: "sixth thoracic vertebrae",
        39: "fifth thoracic vertebrae",
        40: "fourth thoracic vertebrae",
        41: "third thoracic vertebrae",
        42: "second thoracic vertebrae",
        43: "first thoracic vertebrae",
        44: "seventh cervical vertebrae",
        45: "sixth cervical vertebrae",
        46: "fifth cervical vertebrae",
        47: "fourth cervical vertebrae",
        48: "third cervical vertebrae",
        49: "second cervical vertebrae",
        50: "first cervical vertebrae",
        51: "heart",
        52: "aorta",
        53: "pulmonary vein",
        54: "brachiocephalic trunk",
        55: "right subclavian artery",
        56: "left subclavian artery",
        57: "right common carotid artery",
        58: "left common carotid artery",
        59: "left brachiocephalic vein",
        60: "right brachiocephalic vein",
        61: "left atrial appendage",
        62: "superior vena cava",
        63: "inferior vena cava",
        64: "hepatic portal vein",
        65: "left common iliac artery",
        66: "right common iliac artery",
        67: "left common iliac vein",
        68: "right common iliac vein",
        69: "left humerus",
        70: "right humerus",
        71: "left scapula",
        72: "right scapula",
        73: "left clavicle",
        74: "right clavicle",
        75: "left femur",
        76: "right femur",
        77: "left hip",
        78: "right hip",
        79: "spinal cord",
        80: "left gluteus maximus muscle",
        81: "right gluteus maximus muscle",
        82: "left gluteus medius muscle",
        83: "right gluteus medius muscle",
        84: "left gluteus minimus muscle",
        85: "right gluteus minimus muscle",
        86: "left autochthon",
        87: "right autochthon",
        88: "left iliopsoas muscle",
        89: "right iliopsoas muscle",
        90: "brain",
        91: "skull",
        92: "fourth right rib",
        93: "third right rib",
        94: "first left rib",
        95: "second left rib",
        96: "third left rib",
        97: "fourth left rib",
        98: "fifth left rib",
        99: "sixth left rib",
        100: "seventh left rib",
        101: "eighth left rib",
        102: "ninth left rib",
        103: "tenth left rib",
        104: "eleventh left rib",
        105: "twelfth left rib",
        106: "first right rib",
        107: "second right rib",
        108: "fifth right rib",
        109: "sixth right rib",
        110: "seventh right rib",
        111: "eighth right rib",
        112: "ninth right rib",
        113: "tenth right rib",
        114: "eleventh right rib",
        115: "twelfth right rib",
        116: "sternum",
        117: "costal cartilages"
    }
# pprint({idx:v for idx, (k, v) in enumerate(a.items())}, sort_dicts=False)

class_description = {
	1: 'This region represents the spleen. Neighboring structures include the stomach and left kidney.',
	2: 'This region represents the right kidney. Neighboring structures include the liver and colon.',
	3: 'This region represents the left kidney. Neighboring structures include the spleen and stomach.',
	4: 'This region represents the gallbladder. Neighboring structures include the duodenum and right kidney.',
	5: 'This region represents the liver. Neighboring structures include the gallbladder and right kidney.',
	6: 'This region represents the stomach. Neighboring structures include the spleen and left kidney.',
	7: 'This region represents the pancreas. Neighboring structures include the stomach and spleen.',
	8: 'This region represents the right suprarenal gland. Neighboring structures include the liver and inferior vena cava.',
	9: 'This region represents the left suprarenal gland. Neighboring structures include the spleen and stomach.',
	10: 'This region represents the superior lobe of the left lung. Neighboring structures include the trachea and heart.',
	11: 'This region represents the inferior lobe of the left lung. Neighboring structures include the heart and trachea.',
	12: 'This region represents the superior lobe of the right lung. Neighboring structures include the middle lobe and heart.',
	13: 'This region represents the middle lobe of the right lung. Neighboring structures include the heart and superior lobe.',
	14: 'This region represents the inferior lobe of the right lung. Neighboring structures include the heart and middle lobe.',
	15: 'This region represents the esophagus. Neighboring structures include the trachea and thyroid gland.',
	16: 'This region represents the trachea. Neighboring structures include the esophagus and thyroid gland.',
	17: 'This region represents the thyroid gland. Neighboring structures include the trachea and esophagus.',
	18: 'This region represents the small intestine. Neighboring structures include the colon and duodenum.',
	19: 'This region represents the duodenum. Neighboring structures include the gallbladder and small intestine.',
	20: 'This region represents the colon. Neighboring structures include the small intestine and liver.',
	21: 'This region represents the urinary bladder. Neighboring structures include the prostate and sacrum.',
	22: 'This region represents the prostate. Neighboring structures include the sacrum and urinary bladder.',
	23: 'This region represents a cyst in the left kidney. Neighboring structures include the spleen and stomach.',
	24: 'This region represents a cyst in the right kidney. Neighboring structures include the liver and colon.',
	25: 'This region represents the sacrum. Neighboring structures include the lumbar vertebrae and coccyx.',
	26: 'This region represents the first sacral vertebra. Neighboring structures include the lumbar vertebrae and sacrum.',
	27: 'This region represents the fifth lumbar vertebra. Neighboring structures include the sacrum and fourth lumbar vertebra.',
	28: 'This region represents the fourth lumbar vertebra. Neighboring structures include the fifth lumbar vertebra and sacrum.',
	29: 'This region represents the third lumbar vertebra. Neighboring structures include the second and fourth lumbar vertebrae.',
	30: 'This region represents the second lumbar vertebra. Neighboring structures include the first and third lumbar vertebrae.',
	31: 'This region represents the first lumbar vertebra. Neighboring structures include the second lumbar vertebra and sacrum.',
	32: 'This region represents the twelfth thoracic vertebra. Neighboring structures include the eleventh thoracic vertebra and first lumbar vertebra.',
	33: 'This region represents the eleventh thoracic vertebra. Neighboring structures include the twelfth thoracic vertebra and tenth thoracic vertebra.',
	34: 'This region represents the tenth thoracic vertebra. Neighboring structures include the eleventh thoracic vertebra and ninth thoracic vertebra.',
	35: 'This region represents the ninth thoracic vertebra. Neighboring structures include the tenth thoracic vertebra and eighth thoracic vertebra.',
	36: 'This region represents the eighth thoracic vertebra. Neighboring structures include the ninth thoracic vertebra and seventh thoracic vertebra.',
	37: 'This region represents the seventh thoracic vertebra. Neighboring structures include the eighth thoracic vertebra and sixth thoracic vertebra.',
	38: 'This region represents the sixth thoracic vertebra. Neighboring structures include the seventh thoracic vertebra and fifth thoracic vertebra.',
	39: 'This region represents the fifth thoracic vertebra. Neighboring structures include the sixth thoracic vertebra and fourth thoracic vertebra.',
	40: 'This region represents the fourth thoracic vertebra. Neighboring structures include the fifth thoracic vertebra and third thoracic vertebra.',
	41: 'This region represents the third thoracic vertebra. Neighboring structures include the fourth thoracic vertebra and second thoracic vertebra.',
	42: 'This region represents the second thoracic vertebra. Neighboring structures include the third thoracic vertebra and first thoracic vertebra.',
	43: 'This region represents the first thoracic vertebra. Neighboring structures include the second thoracic vertebra.',
	44: 'This region represents the seventh cervical vertebra. Neighboring structures include the sixth cervical vertebra and first thoracic vertebra.',
	45: 'This region represents the sixth cervical vertebra. Neighboring structures include the seventh cervical vertebra and fifth cervical vertebra.',
	46: 'This region represents the fifth cervical vertebra. Neighboring structures include the sixth cervical vertebra and fourth cervical vertebra.',
	47: 'This region represents the fourth cervical vertebra. Neighboring structures include the fifth cervical vertebra and third cervical vertebra.',
	48: 'This region represents the third cervical vertebra. Neighboring structures include the fourth cervical vertebra and second cervical vertebra.',
	49: 'This region represents the second cervical vertebra. Neighboring structures include the third cervical vertebra and first cervical vertebra.',
	50: 'This region represents the first cervical vertebra. Neighboring structures include the second cervical vertebra.',
	51: 'This region represents the heart. Neighboring structures include the lungs, ribs, and sternum.',
	52: 'This region represents the aorta. Neighboring structures include the heart, lungs, and vertebral column.',
	53: 'This region represents a pulmonary vein. Neighboring structures include the heart and bronchi.',
	54: 'This region represents the brachiocephalic trunk. Neighboring structures include the aorta and subclavian arteries.',
	55: 'This region represents the right subclavian artery. Neighboring structures include the brachiocephalic trunk and aorta.',
	56: 'This region represents the left subclavian artery. Neighboring structures include the brachiocephalic trunk and aorta.',
	57: 'This region represents the right common carotid artery. Neighboring structures include the brachiocephalic trunk and aorta.',
	58: 'This region represents the left common carotid artery. Neighboring structures include the brachiocephalic trunk and aorta.',
	59: 'This region represents the left brachiocephalic vein. Neighboring structures include the superior vena cava and aorta.',
	60: 'This region represents the right brachiocephalic vein. Neighboring structures include the superior vena cava and aorta.',
	61: 'This region represents the left atrial appendage. Neighboring structures include the heart and lungs.',
	62: 'This region represents the superior vena cava. Neighboring structures include the heart and aorta.',
	63: 'This region represents the inferior vena cava. Neighboring structures include the liver and heart.',
	64: 'This region represents the hepatic portal vein. Neighboring structures include the liver and inferior vena cava.',
	65: 'This region represents the left common iliac artery. Neighboring structures include the aorta and inferior vena cava.',
	66: 'This region represents the right common iliac artery. Neighboring structures include the aorta and inferior vena cava.',
	67: 'This region represents the left common iliac vein. Neighboring structures include the inferior vena cava and right common iliac vein.',
	68: 'This region represents the right common iliac vein. Neighboring structures include the inferior vena cava and left common iliac vein.',
	69: 'This region represents the left humerus. Neighboring structures include the scapula and clavicle.',
	70: 'This region represents the right humerus. Neighboring structures include the scapula and clavicle.',
	71: 'This region represents the left scapula. Neighboring structures include the ribs, spine, and left clavicle.',
	72: 'This region represents the right scapula. Neighboring structures include the ribs, spine, and right clavicle.',
	73: 'This region represents the left clavicle. Neighboring structures include the ribs, sternum, and left scapula.',
	74: 'This region represents the right clavicle. Neighboring structures include the ribs, sternum, and right scapula.',
	75: 'This region represents the left femur. Neighboring structures include the hip joint and pelvic bones.',
	76: 'This region represents the right femur. Neighboring structures include the hip joint and pelvic bones.',
	77: 'This region represents the left hip. Neighboring structures include the femur, sacrum, and pelvic bones.',
	78: 'This region represents the right hip. Neighboring structures include the femur, sacrum, and pelvic bones.',
	79: 'This region represents the spinal cord. Neighboring structures include the vertebrae and surrounding neural tissues.',
	80: 'This region represents the left gluteus maximus muscle. Neighboring structures include the hip joint and pelvic bones.',
	81: 'This region represents the right gluteus maximus muscle. Neighboring structures include the hip joint and pelvic bones.',
	82: 'This region represents the left gluteus medius muscle. Neighboring structures include the hip joint and pelvic bones.',
	83: 'This region represents the right gluteus medius muscle. Neighboring structures include the hip joint and pelvic bones.',
	84: 'This region represents the left gluteus minimus muscle. Neighboring structures include the hip joint and pelvic bones.',
	85: 'This region represents the right gluteus minimus muscle. Neighboring structures include the hip joint and pelvic bones.',
	86: 'This region represents the left autochthon. Neighboring structures include the hip joint and pelvic bones.',
	87: 'This region represents the right autochthon. Neighboring structures include the hip joint and pelvic bones.',
	88: 'This region represents the left iliopsoas muscle. Neighboring structures include the hip joint and pelvic bones.',
	89: 'This region represents the right iliopsoas muscle. Neighboring structures include the hip joint and pelvic bones.',
	90: 'This region represents the brain. Neighboring structures include the skull.',
	91: 'This region represents the skull. Neighboring structures include the brain.',
	92: 'This region represents the fourth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	93: 'This region represents the third right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	94: 'This region represents the first left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	95: 'This region represents the second left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	96: 'This region represents the third left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	97: 'This region represents the fourth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	98: 'This region represents the fifth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	99: 'This region represents the sixth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	100: 'This region represents the seventh left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	101: 'This region represents the eighth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	102: 'This region represents the ninth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	103: 'This region represents the tenth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	104: 'This region represents the eleventh left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	105: 'This region represents the twelfth left rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	106: 'This region represents the first right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	107: 'This region represents the second right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	108: 'This region represents the fifth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	109: 'This region represents the sixth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	110: 'This region represents the seventh right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	111: 'This region represents the eighth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	112: 'This region represents the ninth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	113: 'This region represents the tenth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	114: 'This region represents the eleventh right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	115: 'This region represents the twelfth right rib. Neighboring structures include the sternum, adjacent ribs, and thoracic vertebrae.',
	116: 'This region represents the sternum. Neighboring structures include the ribs, sternoclavicular joints, and thoracic vertebrae.',
	117: 'This region represents the costal cartilages. Neighboring structures include the ribs, sternum, and thoracic vertebrae.',
    }